# mysql数据源
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.206.150:3306/gulimall_pms?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.206.150:8848
  application:
    name: guli-product
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto
# 启动端口
server:
  port: 8085
# 项目名称